### ISSUE TITLE
Metadata ctor is incorrect

### ISSUE THREAD

**Issue by AzuStar** [Drake53/CSharp.lua#2]
I have a unit constructor that looks like this:
```csharp
 protected NoxUnit(unit u, Stats initialStats = null) { ... }
```
Units are instantiated through Activator.CreateInstance
```csharp
(NoxUnit)Activator.CreateInstance(CustomTypes[GetUnitTypeId(u)], u);
```

Lua exportMetadata exports this .ctor metadata
```lua
 methods = {
            { ".ctor", 0x206, nil, out.War3Api.Common.unit, out.NoxRaven.UnitAgents.Stats },
```

When launching the game, create instance returns nothing because it cannot find proper ctor.
The error I get is 
```
Site: "System.MissingMethodException",
Message: "Specified method could not be found."
```

**Comment by AzuStar** [comment]
This issue might have to be escalated to original LuaCsharp beucase I found more methods with exported metadata get broken, usually ones with predefined default value like `DoStuff(string test = "default value")`

**Comment by Drake53** [comment]
I can't transfer this issue upstream so you'll have to create a new issue in the original CSharpLua repository.
