### ISSUE TITLE
Update to CSharp.lua 2.0?

### ISSUE THREAD

**Issue by KrayOristine** [Drake53/CSharp.lua#4]
Any chance for this to be up to date compared to the original [CSharp.lua 2.0](https://github.com/yanghuan/CSharp.lua/releases/tag/2.0)?

It has been released month ago.

**Comment by Drake53** [comment]
I have merged the latest changes from the upstream repo, but I have not yet updated the nuget package. I'd like to release it together with the next version of War3Net which I'm currently working on. Hoping to finish that this week.

**Comment by Drake53** [comment]
Been busy and still have a lot of work to do on War3Net, so in the meantime I updated CSharpLua to v2.0.0-preview.2, sorry for the delay.
