### ISSUE TITLE
How to use with .NET 7?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [Drake53/CSharp.lua#5]
I have successfully built it with `dotnet build /p:Configuration=Release CSharp.lua.sln`. But when I tried to run it, it always said it needs .NET 6. It refused to run on my .NET 7 even if I forced via `dotnet CSharp.Lua.Launcher.dll`.

**Comment by Drake53** [comment]
I only have this fork for the library / nuget package, I don't use the launcher project, so I also can't answer your question in https://github.com/yanghuan/CSharp.lua/issues/426
