### ISSUE TITLE
Defining alternative base types

### ISSUE THREAD

**Issue by Orden4** [Drake53/CSharp.lua#8]
WCSharp.Api is basically good to go, but has one bit that is a bit of a problem. I know there's various solutions to the problem, but I figured I'd just make an issue here to see if we can perhaps address it in a squeaky clean way, or if I'm just gonna have to hack my way in.

Simply put, War3Api is partially defined within CSharpLua, namely here: https://github.com/Drake53/CSharp.lua/blob/master/CSharp.lua/CoreSystem.Lua/CoreSystem/Common.lua
So for one, even if one opts to use WCSharp.Api, the War3Api types will still be defined, but most importantly, WCSharp.Api basically needs to do the same thing in order for the map to actually launch, as currently it will try to reference non-existent base types since all of the actual WCSharp API is marked with `@CSharpLua.Ignore`, just like War3Api.

The two obvious options seem to be:
1. Use the War3Api namespace myself - On the plus side, this means that switching between the two is seamless, but on the flip side, it's kind of really bad practice.
2. Append a `.lua` plain file into the API that can be injected into the compiler during building to define WCSharp.Api types, but this involves more effort on the user and doesn't address the unused War3Api type definitions.

Do you have any suggestions on how you would approach this? It doesn't really have to be perfect right away, I'm mostly intending to get a initial v0.0.1 out for now and then iterate for probably a couple months before a proper release.

**Comment by Drake53** [comment]
I'd keep it simple: https://github.com/Drake53/CSharp.lua/commit/d8acdb917b6be4cca79ea26a5fb9f0dd33213781

**Comment by Orden4** [comment]
Hm, I see, I'm not entirely sure if I understood it right, but for the time being I got it working with some fairly minimal additions: https://github.com/Orden4/WCSharp/wiki/WCSharp.Api#transitioning-from-war3api-to-wcsharpapi
This will do for now at least. I'll probably come over to bug you for another CSharpLua update after I get around to issuing some additional fixes in a few months time, but I'm good for now. Thanks for the support.
